# Generated by Django 5.1 on 2024-08-25 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iron_ingot', models.PositiveIntegerField(default=0)),
                ('copper_ingot', models.PositiveIntegerField(default=0)),
                ('quartz_ingot', models.PositiveIntegerField(default=0)),
                ('amber_ingot', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed_materials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RawResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone', models.PositiveIntegerField(default=0)),
                ('iron', models.PositiveIntegerField(default=0)),
                ('copper', models.PositiveIntegerField(default=0)),
                ('quartz', models.PositiveIntegerField(default=0)),
                ('amber', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
